---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: tls-secret-name
type: kubernetes.io/tls
data:
# This doesn't need to pass yamllint checking as it's just an example from p. 99
  tls.crt: { base64 encoded cert }
  tls.key: { base64 encoded private key }
